// 
// Decompiled by Procyon v0.5.36
// 

public class afi
{
    public static final afh a;
    public static final afh b;
    public static final ahe c;
    public static final afh d;
    public static final afh e;
    public static final afh f;
    public static final afh g;
    public static final afh h;
    public static final agl i;
    public static final ajw j;
    public static final agl k;
    public static final ajw l;
    public static final ajh m;
    public static final afh n;
    public static final afh o;
    public static final afh p;
    public static final afh q;
    public static final afh r;
    public static final afh s;
    public static final ahs t;
    public static final ahs u;
    public static final afh v;
    public static final afh w;
    public static final afh x;
    public static final afh y;
    public static final afh z;
    public static final afh A;
    public static final afh B;
    public static final afh C;
    public static final afh D;
    public static final afh E;
    public static final als F;
    public static final afh G;
    public static final akc H;
    public static final agb I;
    public static final als J;
    public static final alt K;
    public static final afh L;
    public static final alv M;
    public static final agw N;
    public static final agw O;
    public static final afm P;
    public static final afm Q;
    public static final afh R;
    public static final afh S;
    public static final ahh T;
    public static final ahh U;
    public static final afh V;
    public static final afh W;
    public static final afh X;
    public static final afh Y;
    public static final afh Z;
    public static final afh aa;
    public static final agv ab;
    public static final afh ac;
    public static final afh ad;
    public static final afs ae;
    public static final ajb af;
    public static final afh ag;
    public static final afh ah;
    public static final afh ai;
    public static final afh aj;
    public static final afh ak;
    public static final afh al;
    public static final afh am;
    public static final afh an;
    public static final afh ao;
    public static final afh ap;
    public static final afh aq;
    public static final afh ar;
    public static final afh as;
    public static final afh at;
    public static final afh au;
    public static final afh av;
    public static final afh aw;
    public static final afh ax;
    public static final afh ay;
    public static final afh az;
    public static final afh aA;
    public static final afh aB;
    public static final afh aC;
    public static final afh aD;
    public static final afh aE;
    public static final afh aF;
    public static final afh aG;
    public static final afh aH;
    public static final afh aI;
    public static final afh aJ;
    public static final afo aK;
    public static final afh aL;
    public static final aje aM;
    public static final afh aN;
    public static final afh aO;
    public static final afh aP;
    public static final afh aQ;
    public static final afh aR;
    public static final afh aS;
    public static final afh aT;
    public static final afh aU;
    public static final afh aV;
    public static final afh aW;
    public static final afh aX;
    public static final aip aY;
    public static final afh aZ;
    public static final afh ba;
    public static final ajf bb;
    public static final ajf bc;
    public static final afh bd;
    public static final afh be;
    public static final afh bf;
    public static final afh bg;
    public static final afh bh;
    public static final afh bi;
    public static final afh bj;
    public static final afh bk;
    public static final afh bl;
    public static final afh bm;
    public static final afh bn;
    public static final afh bo;
    public static final afh bp;
    public static final afh bq;
    public static final afh br;
    public static final afh bs;
    public static final afh bt;
    public static final afh bu;
    public static final afh bv;
    public static final aib bw;
    public static final afh bx;
    public static final afh by;
    public static final afh bz;
    public static final afh bA;
    public static final afh bB;
    public static final afh bC;
    public static final afh bD;
    public static final afr bE;
    public static final afh bF;
    public static final afh bG;
    public static final afh bH;
    public static final afh bI;
    public static final afh bJ;
    public static final afh bK;
    public static final ahh bL;
    public static final ahh bM;
    public static final afh bN;
    public static final afh bO;
    public static final afh bP;
    public static final afh bQ;
    public static final akj bR;
    public static final afh bS;
    public static final afh bT;
    public static final afh bU;
    public static final afh bV;
    public static final afh bW;
    public static final afh bX;
    public static final aff bY;
    public static final afh bZ;
    public static final afh ca;
    public static final afh cb;
    public static final afh cc;
    public static final afh cd;
    public static final ajm ce;
    public static final afh cf;
    public static final afh cg;
    public static final afh ch;
    public static final afh ci;
    public static final afx cj;
    public static final afx ck;
    public static final aga cl;
    public static final aga cm;
    public static final afh cn;
    public static final afh co;
    public static final ahn cp;
    public static final afh cq;
    public static final afh cr;
    public static final afh cs;
    public static final afh ct;
    public static final afh cu;
    public static final afh cv;
    public static final afh cw;
    public static final afh cx;
    public static final afh cy;
    public static final afh cz;
    public static final afh cA;
    public static final afh cB;
    public static final afh cC;
    public static final afh cD;
    public static final afh cE;
    public static final agi cF;
    public static final ajs cG;
    public static final ajt cH;
    public static final afh cI;
    public static final afh cJ;
    public static final afh cK;
    public static final afh cL;
    public static final afh cM;
    public static final afh cN;
    public static final ahh cO;
    public static final ahh cP;
    
    private static afh a(final String \u2603) {
        return afh.c.a(new jy(\u2603));
    }
    
    static {
        if (!kb.a()) {
            throw new RuntimeException("Accessed Blocks before Bootstrap!");
        }
        a = a("air");
        b = a("stone");
        c = (ahe)a("grass");
        d = a("dirt");
        e = a("cobblestone");
        f = a("planks");
        g = a("sapling");
        h = a("bedrock");
        i = (agl)a("flowing_water");
        j = (ajw)a("water");
        k = (agl)a("flowing_lava");
        l = (ajw)a("lava");
        m = (ajh)a("sand");
        n = a("gravel");
        o = a("gold_ore");
        p = a("iron_ore");
        q = a("coal_ore");
        r = a("log");
        s = a("log2");
        t = (ahs)a("leaves");
        u = (ahs)a("leaves2");
        v = a("sponge");
        w = a("glass");
        x = a("lapis_ore");
        y = a("lapis_block");
        z = a("dispenser");
        A = a("sandstone");
        B = a("noteblock");
        C = a("bed");
        D = a("golden_rail");
        E = a("detector_rail");
        F = (als)a("sticky_piston");
        G = a("web");
        H = (akc)a("tallgrass");
        I = (agb)a("deadbush");
        J = (als)a("piston");
        K = (alt)a("piston_head");
        L = a("wool");
        M = (alv)a("piston_extension");
        N = (agw)a("yellow_flower");
        O = (agw)a("red_flower");
        P = (afm)a("brown_mushroom");
        Q = (afm)a("red_mushroom");
        R = a("gold_block");
        S = a("iron_block");
        T = (ahh)a("double_stone_slab");
        U = (ahh)a("stone_slab");
        V = a("brick_block");
        W = a("tnt");
        X = a("bookshelf");
        Y = a("mossy_cobblestone");
        Z = a("obsidian");
        aa = a("torch");
        ab = (agv)a("fire");
        ac = a("mob_spawner");
        ad = a("oak_stairs");
        ae = (afs)a("chest");
        af = (ajb)a("redstone_wire");
        ag = a("diamond_ore");
        ah = a("diamond_block");
        ai = a("crafting_table");
        aj = a("wheat");
        ak = a("farmland");
        al = a("furnace");
        am = a("lit_furnace");
        an = a("standing_sign");
        ao = a("wooden_door");
        ap = a("spruce_door");
        aq = a("birch_door");
        ar = a("jungle_door");
        as = a("acacia_door");
        at = a("dark_oak_door");
        au = a("ladder");
        av = a("rail");
        aw = a("stone_stairs");
        ax = a("wall_sign");
        ay = a("lever");
        az = a("stone_pressure_plate");
        aA = a("iron_door");
        aB = a("wooden_pressure_plate");
        aC = a("redstone_ore");
        aD = a("lit_redstone_ore");
        aE = a("unlit_redstone_torch");
        aF = a("redstone_torch");
        aG = a("stone_button");
        aH = a("snow_layer");
        aI = a("ice");
        aJ = a("snow");
        aK = (afo)a("cactus");
        aL = a("clay");
        aM = (aje)a("reeds");
        aN = a("jukebox");
        aO = a("fence");
        aP = a("spruce_fence");
        aQ = a("birch_fence");
        aR = a("jungle_fence");
        aS = a("dark_oak_fence");
        aT = a("acacia_fence");
        aU = a("pumpkin");
        aV = a("netherrack");
        aW = a("soul_sand");
        aX = a("glowstone");
        aY = (aip)a("portal");
        aZ = a("lit_pumpkin");
        ba = a("cake");
        bb = (ajf)a("unpowered_repeater");
        bc = (ajf)a("powered_repeater");
        bd = a("trapdoor");
        be = a("monster_egg");
        bf = a("stonebrick");
        bg = a("brown_mushroom_block");
        bh = a("red_mushroom_block");
        bi = a("iron_bars");
        bj = a("glass_pane");
        bk = a("melon_block");
        bl = a("pumpkin_stem");
        bm = a("melon_stem");
        bn = a("vine");
        bo = a("fence_gate");
        bp = a("spruce_fence_gate");
        bq = a("birch_fence_gate");
        br = a("jungle_fence_gate");
        bs = a("dark_oak_fence_gate");
        bt = a("acacia_fence_gate");
        bu = a("brick_stairs");
        bv = a("stone_brick_stairs");
        bw = (aib)a("mycelium");
        bx = a("waterlily");
        by = a("nether_brick");
        bz = a("nether_brick_fence");
        bA = a("nether_brick_stairs");
        bB = a("nether_wart");
        bC = a("enchanting_table");
        bD = a("brewing_stand");
        bE = (afr)a("cauldron");
        bF = a("end_portal");
        bG = a("end_portal_frame");
        bH = a("end_stone");
        bI = a("dragon_egg");
        bJ = a("redstone_lamp");
        bK = a("lit_redstone_lamp");
        bL = (ahh)a("double_wooden_slab");
        bM = (ahh)a("wooden_slab");
        bN = a("cocoa");
        bO = a("sandstone_stairs");
        bP = a("emerald_ore");
        bQ = a("ender_chest");
        bR = (akj)a("tripwire_hook");
        bS = a("tripwire");
        bT = a("emerald_block");
        bU = a("spruce_stairs");
        bV = a("birch_stairs");
        bW = a("jungle_stairs");
        bX = a("command_block");
        bY = (aff)a("beacon");
        bZ = a("cobblestone_wall");
        ca = a("flower_pot");
        cb = a("carrots");
        cc = a("potatoes");
        cd = a("wooden_button");
        ce = (ajm)a("skull");
        cf = a("anvil");
        cg = a("trapped_chest");
        ch = a("light_weighted_pressure_plate");
        ci = a("heavy_weighted_pressure_plate");
        cj = (afx)a("unpowered_comparator");
        ck = (afx)a("powered_comparator");
        cl = (aga)a("daylight_detector");
        cm = (aga)a("daylight_detector_inverted");
        cn = a("redstone_block");
        co = a("quartz_ore");
        cp = (ahn)a("hopper");
        cq = a("quartz_block");
        cr = a("quartz_stairs");
        cs = a("activator_rail");
        ct = a("dropper");
        cu = a("stained_hardened_clay");
        cv = a("barrier");
        cw = a("iron_trapdoor");
        cx = a("hay_block");
        cy = a("carpet");
        cz = a("hardened_clay");
        cA = a("coal_block");
        cB = a("packed_ice");
        cC = a("acacia_stairs");
        cD = a("dark_oak_stairs");
        cE = a("slime");
        cF = (agi)a("double_plant");
        cG = (ajs)a("stained_glass");
        cH = (ajt)a("stained_glass_pane");
        cI = a("prismarine");
        cJ = a("sea_lantern");
        cK = a("standing_banner");
        cL = a("wall_banner");
        cM = a("red_sandstone");
        cN = a("red_sandstone_stairs");
        cO = (ahh)a("double_stone_slab2");
        cP = (ahh)a("stone_slab2");
    }
}
