// 
// Decompiled by Procyon v0.5.36
// 

public class zy
{
    public static final zw a;
    public static final zw b;
    public static final zw c;
    public static final zw d;
    public static final zw e;
    public static final yt f;
    public static final zw g;
    public static final zw h;
    public static final zw i;
    public static final zw j;
    public static final zw k;
    public static final zw l;
    public static final zw m;
    public static final zw n;
    public static final zw o;
    public static final zw p;
    public static final zw q;
    public static final zw r;
    public static final zw s;
    public static final zw t;
    public static final zw u;
    public static final zw v;
    public static final zw w;
    public static final zw x;
    public static final zw y;
    public static final zw z;
    public static final zw A;
    public static final zw B;
    public static final zw C;
    public static final zw D;
    public static final zw E;
    public static final zw F;
    public static final zw G;
    public static final zw H;
    public static final zw I;
    public static final zw J;
    public static final zw K;
    public static final zw L;
    public static final zw M;
    public static final zw N;
    public static final zw O;
    public static final zw P;
    public static final yj Q;
    public static final yj R;
    public static final yj S;
    public static final yj T;
    public static final yj U;
    public static final yj V;
    public static final yj W;
    public static final yj X;
    public static final yj Y;
    public static final yj Z;
    public static final yj aa;
    public static final yj ab;
    public static final yj ac;
    public static final yj ad;
    public static final yj ae;
    public static final yj af;
    public static final yj ag;
    public static final yj ah;
    public static final yj ai;
    public static final yj aj;
    public static final zw ak;
    public static final zw al;
    public static final zw am;
    public static final zw an;
    public static final zw ao;
    public static final zw ap;
    public static final zw aq;
    public static final zw ar;
    public static final zw as;
    public static final zw at;
    public static final zw au;
    public static final zw av;
    public static final zw aw;
    public static final zw ax;
    public static final zw ay;
    public static final zw az;
    public static final zw aA;
    public static final zw aB;
    public static final zw aC;
    public static final zw aD;
    public static final zw aE;
    public static final zw aF;
    public static final zw aG;
    public static final zw aH;
    public static final zw aI;
    public static final zw aJ;
    public static final zw aK;
    public static final zw aL;
    public static final zw aM;
    public static final zw aN;
    public static final zw aO;
    public static final zw aP;
    public static final zw aQ;
    public static final zq aR;
    public static final zw aS;
    public static final zw aT;
    public static final zw aU;
    public static final zw aV;
    public static final zw aW;
    public static final zw aX;
    public static final zw aY;
    public static final zw aZ;
    public static final zw ba;
    public static final zw bb;
    public static final zw bc;
    public static final aab bd;
    public static final aap be;
    public static final zw bf;
    public static final zw bg;
    public static final zw bh;
    public static final zw bi;
    public static final zw bj;
    public static final zw bk;
    public static final zw bl;
    public static final zw bm;
    public static final zw bn;
    public static final zw bo;
    public static final zw bp;
    public static final zw bq;
    public static final zw br;
    public static final zw bs;
    public static final zw bt;
    public static final zw bu;
    public static final zw bv;
    public static final zw bw;
    public static final zw bx;
    public static final zw by;
    public static final aai bz;
    public static final zw bA;
    public static final zw bB;
    public static final zw bC;
    public static final zw bD;
    public static final zw bE;
    public static final zw bF;
    public static final zw bG;
    public static final zw bH;
    public static final zw bI;
    public static final zw bJ;
    public static final zw bK;
    public static final zw bL;
    public static final zw bM;
    public static final zw bN;
    public static final zw bO;
    public static final zw bP;
    public static final zw bQ;
    public static final zw bR;
    public static final zw bS;
    public static final zw bT;
    public static final zw bU;
    public static final zh bV;
    public static final zw bW;
    public static final zw bX;
    public static final zw bY;
    public static final zw bZ;
    public static final zw ca;
    public static final zw cb;
    public static final zw cc;
    public static final zi cd;
    public static final zw ce;
    public static final zw cf;
    public static final zw cg;
    public static final zw ch;
    public static final zw ci;
    public static final yk cj;
    public static final zw ck;
    public static final zw cl;
    public static final zw cm;
    public static final zw cn;
    public static final zw co;
    public static final zw cp;
    public static final zw cq;
    public static final zw cr;
    public static final zw cs;
    public static final zw ct;
    public static final zw cu;
    public static final zw cv;
    public static final zw cw;
    public static final zw cx;
    public static final zw cy;
    public static final zw cz;
    public static final zw cA;
    public static final zw cB;
    public static final zw cC;
    public static final zw cD;
    public static final zw cE;
    
    private static zw a(final String \u2603) {
        return zw.e.a(new jy(\u2603));
    }
    
    static {
        if (!kb.a()) {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        }
        a = a("iron_shovel");
        b = a("iron_pickaxe");
        c = a("iron_axe");
        d = a("flint_and_steel");
        e = a("apple");
        f = (yt)a("bow");
        g = a("arrow");
        h = a("coal");
        i = a("diamond");
        j = a("iron_ingot");
        k = a("gold_ingot");
        l = a("iron_sword");
        m = a("wooden_sword");
        n = a("wooden_shovel");
        o = a("wooden_pickaxe");
        p = a("wooden_axe");
        q = a("stone_sword");
        r = a("stone_shovel");
        s = a("stone_pickaxe");
        t = a("stone_axe");
        u = a("diamond_sword");
        v = a("diamond_shovel");
        w = a("diamond_pickaxe");
        x = a("diamond_axe");
        y = a("stick");
        z = a("bowl");
        A = a("mushroom_stew");
        B = a("golden_sword");
        C = a("golden_shovel");
        D = a("golden_pickaxe");
        E = a("golden_axe");
        F = a("string");
        G = a("feather");
        H = a("gunpowder");
        I = a("wooden_hoe");
        J = a("stone_hoe");
        K = a("iron_hoe");
        L = a("diamond_hoe");
        M = a("golden_hoe");
        N = a("wheat_seeds");
        O = a("wheat");
        P = a("bread");
        Q = (yj)a("leather_helmet");
        R = (yj)a("leather_chestplate");
        S = (yj)a("leather_leggings");
        T = (yj)a("leather_boots");
        U = (yj)a("chainmail_helmet");
        V = (yj)a("chainmail_chestplate");
        W = (yj)a("chainmail_leggings");
        X = (yj)a("chainmail_boots");
        Y = (yj)a("iron_helmet");
        Z = (yj)a("iron_chestplate");
        aa = (yj)a("iron_leggings");
        ab = (yj)a("iron_boots");
        ac = (yj)a("diamond_helmet");
        ad = (yj)a("diamond_chestplate");
        ae = (yj)a("diamond_leggings");
        af = (yj)a("diamond_boots");
        ag = (yj)a("golden_helmet");
        ah = (yj)a("golden_chestplate");
        ai = (yj)a("golden_leggings");
        aj = (yj)a("golden_boots");
        ak = a("flint");
        al = a("porkchop");
        am = a("cooked_porkchop");
        an = a("painting");
        ao = a("golden_apple");
        ap = a("sign");
        aq = a("wooden_door");
        ar = a("spruce_door");
        as = a("birch_door");
        at = a("jungle_door");
        au = a("acacia_door");
        av = a("dark_oak_door");
        aw = a("bucket");
        ax = a("water_bucket");
        ay = a("lava_bucket");
        az = a("minecart");
        aA = a("saddle");
        aB = a("iron_door");
        aC = a("redstone");
        aD = a("snowball");
        aE = a("boat");
        aF = a("leather");
        aG = a("milk_bucket");
        aH = a("brick");
        aI = a("clay_ball");
        aJ = a("reeds");
        aK = a("paper");
        aL = a("book");
        aM = a("slime_ball");
        aN = a("chest_minecart");
        aO = a("furnace_minecart");
        aP = a("egg");
        aQ = a("compass");
        aR = (zq)a("fishing_rod");
        aS = a("clock");
        aT = a("glowstone_dust");
        aU = a("fish");
        aV = a("cooked_fish");
        aW = a("dye");
        aX = a("bone");
        aY = a("sugar");
        aZ = a("cake");
        ba = a("bed");
        bb = a("repeater");
        bc = a("cookie");
        bd = (aab)a("filled_map");
        be = (aap)a("shears");
        bf = a("melon");
        bg = a("pumpkin_seeds");
        bh = a("melon_seeds");
        bi = a("beef");
        bj = a("cooked_beef");
        bk = a("chicken");
        bl = a("cooked_chicken");
        bm = a("mutton");
        bn = a("cooked_mutton");
        bo = a("rabbit");
        bp = a("cooked_rabbit");
        bq = a("rabbit_stew");
        br = a("rabbit_foot");
        bs = a("rabbit_hide");
        bt = a("rotten_flesh");
        bu = a("ender_pearl");
        bv = a("blaze_rod");
        bw = a("ghast_tear");
        bx = a("gold_nugget");
        by = a("nether_wart");
        bz = (aai)a("potion");
        bA = a("glass_bottle");
        bB = a("spider_eye");
        bC = a("fermented_spider_eye");
        bD = a("blaze_powder");
        bE = a("magma_cream");
        bF = a("brewing_stand");
        bG = a("cauldron");
        bH = a("ender_eye");
        bI = a("speckled_melon");
        bJ = a("spawn_egg");
        bK = a("experience_bottle");
        bL = a("fire_charge");
        bM = a("writable_book");
        bN = a("written_book");
        bO = a("emerald");
        bP = a("item_frame");
        bQ = a("flower_pot");
        bR = a("carrot");
        bS = a("potato");
        bT = a("baked_potato");
        bU = a("poisonous_potato");
        bV = (zh)a("map");
        bW = a("golden_carrot");
        bX = a("skull");
        bY = a("carrot_on_a_stick");
        bZ = a("nether_star");
        ca = a("pumpkin_pie");
        cb = a("fireworks");
        cc = a("firework_charge");
        cd = (zi)a("enchanted_book");
        ce = a("comparator");
        cf = a("netherbrick");
        cg = a("quartz");
        ch = a("tnt_minecart");
        ci = a("hopper_minecart");
        cj = (yk)a("armor_stand");
        ck = a("iron_horse_armor");
        cl = a("golden_horse_armor");
        cm = a("diamond_horse_armor");
        cn = a("lead");
        co = a("name_tag");
        cp = a("command_block_minecart");
        cq = a("record_13");
        cr = a("record_cat");
        cs = a("record_blocks");
        ct = a("record_chirp");
        cu = a("record_far");
        cv = a("record_mall");
        cw = a("record_mellohi");
        cx = a("record_stal");
        cy = a("record_strad");
        cz = a("record_ward");
        cA = a("record_11");
        cB = a("record_wait");
        cC = a("prismarine_shard");
        cD = a("prismarine_crystals");
        cE = a("banner");
    }
}
